# Generated by Django 2.2 on 2021-12-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a description ;odhg;oh sd;ogihdsilhvbksyub vsdkuhbvhj viudsbvuhb hbvchvhscbgva'),
            preserve_default=False,
        ),
    ]
